version: '2'
services:
  # Torrent client
  torrent:
    # https://hub.docker.com/r/linuxserver/transmission
    image: linuxserver/transmission
    ports:
      - "9091:9091" # WebUI ("/transmission/web/")
    volumes:
      - ${DATA}/transmission/config:/config
      - ${DATA}/transmission/watch:/watch
      - ${DATA}/transmission/downloads:/downloads
  # Plex server
  plex:
    image: linuxserver/plex
    restart: unless-stopped
    ports:
      - "32400:32400" # WebUI ("/web")
    volumes:
      - ${DATA}/plex/config:/config
      - ${DATA}/plex/transcode:/transcode
      - ${DATA}/transmission/downloads/complete:/data
