version: "2"
services:
  # Reverse proxy
  proxy:
    image: traefik:1.7
    command:
      - "--docker.domain=${DOMAIN}"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:proxy.${DOMAIN}"
  # File management
  webdav:
    image: bytemark/webdav:2.4
    ports:
      - "8081:80"
    environment:
      - AUTH_TYPE=Digest
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ${DATA}:/var/lib/dav/data
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:webdav.${DOMAIN}"
  filemanager:
    image: filebrowser/filebrowser:v2.0.16
    ports:
      - "8082:80"
    volumes:
      - ${DATA}:/srv
      #- ${DATA}/filemanager/database.db:/database.db
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:filemanager.${DOMAIN}"
  # Torrent client
  torrent:
    # https://hub.docker.com/r/linuxserver/transmission
    image: linuxserver/transmission:2.94-r2-ls36
    ports:
      - "9091:9091" # WebUI ("/transmission/web/")
    volumes:
      - ${DATA}/transmission/config:/config
      - ${DATA}/transmission/watch:/watch
      - ${DATA}/transmission/downloads:/downloads
    labels:
      - "traefik.port=9091"
      - "traefik.frontend.rule=Host:torrent.${DOMAIN}"
  # Plex server
  plex:
    image: linuxserver/plex:1.18.2.2058-e67a4e892-ls71
    restart: unless-stopped
    ports:
      - "32400:32400" # WebUI ("/web")
    volumes:
      - ${DATA}/plex/config:/config
      - ${DATA}/plex/transcode:/transcode
      - ${DATA}/transmission/downloads/complete:/data
    labels:
      - "traefik.port=32400"
      - "traefik.frontend.rule=Host:plex.${DOMAIN}"
